version: "3.8"
services:

  nginx:
    image: nginx:latest
    profiles: ["prod"]
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/prd/templates:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - REDMINE_HOST=${REDMINE_HOST}

  nginx-dev:
    image: nginx:latest
    profiles: ["dev"]
    restart: always
    ports:
      - "8000-9000:8000-9000"
    volumes:
      - ./nginx/dev/templates:/etc/nginx/templates
    environment:
      - REDMINE_HOST=${REDMINE_HOST}

  certbot:
    image: certbot/certbot
    profiles: ["prod"]
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    depends_on:
      - nginx
      - redmine
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  redmine:
    image: redmine:latest
    restart: always
    environment:
      REDMINE_DB_POSTGRES: redmine_db
      REDMINE_DB_USERNAME: ${REDMINE_USERNAME}
      REDMINE_DB_PASSWORD: ${REDMINE_PASSWORD}
      REDMINE_PLUGIN_MIGRATE: 1
    volumes:
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes:/usr/src/redmine/public/themes
    depends_on:
      - redmine_db
      
  redmine_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${REDMINE_PASSWORD}
      POSTGRES_USER: ${REDMINE_USERNAME}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  backup:
    build: ./backup
    profiles: ["prod"]
    volumes:
      - ./redmine/files:/data/redmine/files
      - ./backup/archives:/backup/archives
    environment:
      REDMINE_USERNAME: ${REDMINE_USERNAME}
      REDMINE_PASSWORD: ${REDMINE_PASSWORD}
