version: "3.8"

networks:
  gitea:
    external: false

services:
  nginx:
    image: nginx:latest
    networks:
      - gitea
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/templates:/etc/nginx/templates

  gitea-server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_ID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${GITEA_POSTGRES_USERNAME}
      - GITEA__database__PASSWD=${GITEA_POSTGRES_PASSWORD}
      - 'GITEA__server__ROOT_URL=http://${DOMAIN}/gitea/'
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gitea-db

  gitea-db:
    image: postgres:14
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=${GITEA_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${GITEA_POSTGRES_PASSWORD}
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./postgres/gitea:/var/lib/postgresql/data

  backup:
    build: ./backup
    volumes:
      - ./backup/archives:/backup/archives
      - /var/run/docker.sock:/var/run/docker.sock
